version: '3'
services:
  cnil-pia-back:
    container_name: LINCnil-pia-back
    build: docker/cnil-pia-back
    restart: always
    environment:
      DATABASE_HOST: 'database'
      DATABASE_USERNAME: 'postgres'
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-insecure}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:-insecure}
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
    links:
      - database
    depends_on:
      - database
    ports:
      - 3000:3000
  cnil-pia-front:
    container_name: LINCnil-pia-front
    build: docker/cnil-pia-front
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
  database:
    container_name: LINCnil-pia-db
    image: postgres:11.0
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-insecure}